#!/bin/bash

# This script takes the certs generated by Nginx Proxy Manager
# and copies it to the mailcow docker container.
# Before use, make sure you update the path to your docker data and locate which cert belongs to mailcow

# Copy the certs to the mailcow container
scp root@10.0.0.2:/root/npm/letsencrypt/live/npm-33/fullchain.pem /opt/mailcow-dockerized/data/assets/ssl/cert.pem
scp root@10.0.0.2:/root/npm/letsencrypt/live/npm-33/privkey.pem /opt/mailcow-dockerized/data/assets/ssl/key.pem

# Restart the mailcow container
docker restart $(docker ps -qaf name=postfix-mailcow)
docker restart $(docker ps -qaf name=nginx-mailcow)
docker restart $(docker ps -qaf name=dovecot-mailcow)
